/* 
 * Hockeyapp Public API wrapper
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AppsApps
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AppsAppsTests
    {
        // TODO uncomment below to declare an instance variable for AppsApps
        //private AppsApps instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AppsApps
            //instance = new AppsApps();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AppsApps
        /// </summary>
        [Test]
        public void AppsAppsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AppsApps
            //Assert.IsInstanceOfType<AppsApps> (instance, "variable 'instance' is a AppsApps");
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'BundleIdentifier'
        /// </summary>
        [Test]
        public void BundleIdentifierTest()
        {
            // TODO unit test for the property 'BundleIdentifier'
        }
        /// <summary>
        /// Test the property 'PublicIdentifier'
        /// </summary>
        [Test]
        public void PublicIdentifierTest()
        {
            // TODO unit test for the property 'PublicIdentifier'
        }
        /// <summary>
        /// Test the property 'DeviceFamily'
        /// </summary>
        [Test]
        public void DeviceFamilyTest()
        {
            // TODO unit test for the property 'DeviceFamily'
        }
        /// <summary>
        /// Test the property 'MinimumOsVersion'
        /// </summary>
        [Test]
        public void MinimumOsVersionTest()
        {
            // TODO unit test for the property 'MinimumOsVersion'
        }
        /// <summary>
        /// Test the property 'ReleaseType'
        /// </summary>
        [Test]
        public void ReleaseTypeTest()
        {
            // TODO unit test for the property 'ReleaseType'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Platform'
        /// </summary>
        [Test]
        public void PlatformTest()
        {
            // TODO unit test for the property 'Platform'
        }

    }

}
