#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Hockeyapp Public API wrapper
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 0.0.2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/



@protocol SWGAppsApps
@end

@interface SWGAppsApps : SWGObject


@property(nonatomic) NSString* title;

@property(nonatomic) NSString* bundleIdentifier;

@property(nonatomic) NSString* publicIdentifier;

@property(nonatomic) NSString* deviceFamily;

@property(nonatomic) NSString* minimumOsVersion;

@property(nonatomic) NSNumber* releaseType;

@property(nonatomic) NSNumber* status;

@property(nonatomic) NSString* platform;

@end
