/**
 * Hockeyapp Public API wrapper
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HockeyappPublicApiWrapper) {
      root.HockeyappPublicApiWrapper = {};
    }
    root.HockeyappPublicApiWrapper.App = factory(root.HockeyappPublicApiWrapper.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The App model module.
   * @module model/App
   * @version 0.0.2
   */

  /**
   * Constructs a new <code>App</code>.
   * @alias module:model/App
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>App</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/App} obj Optional instance to populate.
   * @return {module:model/App} The populated <code>App</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('bundle_identifier')) {
        obj['bundle_identifier'] = ApiClient.convertToType(data['bundle_identifier'], 'String');
      }
      if (data.hasOwnProperty('public_identifier')) {
        obj['public_identifier'] = ApiClient.convertToType(data['public_identifier'], 'String');
      }
      if (data.hasOwnProperty('release_type')) {
        obj['release_type'] = ApiClient.convertToType(data['release_type'], 'Number');
      }
      if (data.hasOwnProperty('platform')) {
        obj['platform'] = ApiClient.convertToType(data['platform'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * @member {String} bundle_identifier
   */
  exports.prototype['bundle_identifier'] = undefined;
  /**
   * @member {String} public_identifier
   */
  exports.prototype['public_identifier'] = undefined;
  /**
   * @member {Number} release_type
   */
  exports.prototype['release_type'] = undefined;
  /**
   * @member {module:model/App.PlatformEnum} platform
   */
  exports.prototype['platform'] = undefined;


  /**
   * Allowed values for the <code>platform</code> property.
   * @enum {String}
   * @readonly
   */
  exports.PlatformEnum = {
    /**
     * value: "iOS"
     * @const
     */
    "iOS": "iOS",
    /**
     * value: "Android"
     * @const
     */
    "Android": "Android",
    /**
     * value: "Mac Os"
     * @const
     */
    "Mac Os": "Mac Os",
    /**
     * value: "Windows Phone"
     * @const
     */
    "Windows Phone": "Windows Phone",
    /**
     * value: "Custom"
     * @const
     */
    "Custom": "Custom"  };


  return exports;
}));


