=begin
#Hockeyapp Public API wrapper

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.0.2

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require "uri"

module SwaggerClient
  class DefaultApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # 
    # Gets `Apps`. 
    # @param [Hash] opts the optional parameters
    # @return [Apps]
    def apps_get(opts = {})
      data, _status_code, _headers = apps_get_with_http_info(opts)
      return data
    end

    # 
    # Gets &#x60;Apps&#x60;. 
    # @param [Hash] opts the optional parameters
    # @return [Array<(Apps, Fixnum, Hash)>] Apps data, response status code and response headers
    def apps_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: DefaultApi.apps_get ..."
      end
      # resource path
      local_var_path = "/apps".sub('{format}','json')

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = []
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = []
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['token']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Apps')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#apps_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # Upload a new app
    # @param ipa file data of the .ipa for iOS, .app.zip for OS X, or .apk file for Android
    # @param [Hash] opts the optional parameters
    # @option opts [File] :dsym file data of the .dSYM.zip file (iOS and OS X) or mapping.txt (Android); note that the extension has to be .dsym.zip (case-insensitive) for iOS and OS X and the file name has to be mapping.txt for Android.
    # @option opts [String] :notes release notes as Textile or Markdown (after 5k characters note are truncated)
    # @option opts [Integer] :notes_type type of release notes. &#x60;0&#x60; for Textile, &#x60;1&#x60; for Markdown
    # @option opts [Integer] :notify notify testers (can only be set with full-access tokens). &#x60;0&#x60; to not notify, &#x60;1&#x60; to notify all testers that can install this app,  &#x60;2&#x60; to notify all testers
    # @option opts [Integer] :status download status (can only be set with full-access tokens). &#x60;1&#x60; to not allow users to download the version, &#x60;2&#x60; to make the version available for download
    # @option opts [String] :strategy replace or add build with same build number. &#x60;add&#x60; to add the build as a new build to even if it has the same build number __default__, &#x60;replace&#x60; to replace to a build with the same build number
    # @option opts [Array<String>] :tags restrict download to comma-separated list of tags
    # @option opts [Array<Integer>] :teams restrict download to comma-separated list of team IDs
    # @option opts [Array<Integer>] :users restrict download to comma-separated list of user IDs
    # @option opts [Integer] :mandatory set version as mandatory &#x60;0&#x60; for not mandatory __default__, &#x60;1&#x60; for mandatory
    # @option opts [Integer] :release_type set the release type of the app. &#x60;0&#x60; for beta __default__  &#x60;1&#x60; for store &#x60;2&#x60; for alpha &#x60;3&#x60; for enterprise
    # @option opts [BOOLEAN] :private set to &#x60;true&#x60; to enable the private download page (default is &#x60;true&#x60;)
    # @option opts [Integer] :owner_id set to the ID of your organization
    # @option opts [String] :commit_sha set to the git commit sha for this build
    # @option opts [String] :build_server_url set to the URL of the build job on your build server
    # @option opts [String] :repository_url set to your source repository
    # @return [App]
    def apps_upload_post(ipa, opts = {})
      data, _status_code, _headers = apps_upload_post_with_http_info(ipa, opts)
      return data
    end

    # 
    # Upload a new app
    # @param ipa file data of the .ipa for iOS, .app.zip for OS X, or .apk file for Android
    # @param [Hash] opts the optional parameters
    # @option opts [File] :dsym file data of the .dSYM.zip file (iOS and OS X) or mapping.txt (Android); note that the extension has to be .dsym.zip (case-insensitive) for iOS and OS X and the file name has to be mapping.txt for Android.
    # @option opts [String] :notes release notes as Textile or Markdown (after 5k characters note are truncated)
    # @option opts [Integer] :notes_type type of release notes. &#x60;0&#x60; for Textile, &#x60;1&#x60; for Markdown
    # @option opts [Integer] :notify notify testers (can only be set with full-access tokens). &#x60;0&#x60; to not notify, &#x60;1&#x60; to notify all testers that can install this app,  &#x60;2&#x60; to notify all testers
    # @option opts [Integer] :status download status (can only be set with full-access tokens). &#x60;1&#x60; to not allow users to download the version, &#x60;2&#x60; to make the version available for download
    # @option opts [String] :strategy replace or add build with same build number. &#x60;add&#x60; to add the build as a new build to even if it has the same build number __default__, &#x60;replace&#x60; to replace to a build with the same build number
    # @option opts [Array<String>] :tags restrict download to comma-separated list of tags
    # @option opts [Array<Integer>] :teams restrict download to comma-separated list of team IDs
    # @option opts [Array<Integer>] :users restrict download to comma-separated list of user IDs
    # @option opts [Integer] :mandatory set version as mandatory &#x60;0&#x60; for not mandatory __default__, &#x60;1&#x60; for mandatory
    # @option opts [Integer] :release_type set the release type of the app. &#x60;0&#x60; for beta __default__  &#x60;1&#x60; for store &#x60;2&#x60; for alpha &#x60;3&#x60; for enterprise
    # @option opts [BOOLEAN] :private set to &#x60;true&#x60; to enable the private download page (default is &#x60;true&#x60;)
    # @option opts [Integer] :owner_id set to the ID of your organization
    # @option opts [String] :commit_sha set to the git commit sha for this build
    # @option opts [String] :build_server_url set to the URL of the build job on your build server
    # @option opts [String] :repository_url set to your source repository
    # @return [Array<(App, Fixnum, Hash)>] App data, response status code and response headers
    def apps_upload_post_with_http_info(ipa, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: DefaultApi.apps_upload_post ..."
      end
      # verify the required parameter 'ipa' is set
      fail ArgumentError, "Missing the required parameter 'ipa' when calling DefaultApi.apps_upload_post" if ipa.nil?
      if opts[:'strategy'] && !['add', 'replace'].include?(opts[:'strategy'])
        fail ArgumentError, 'invalid value for "strategy", must be one of add, replace'
      end
      # resource path
      local_var_path = "/apps/upload".sub('{format}','json')

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['multipart/form-data']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}
      form_params["Ipa"] = ipa
      form_params["dsym"] = opts[:'dsym'] if !opts[:'dsym'].nil?
      form_params["notes"] = opts[:'notes'] if !opts[:'notes'].nil?
      form_params["notes_type"] = opts[:'notes_type'] if !opts[:'notes_type'].nil?
      form_params["notify"] = opts[:'notify'] if !opts[:'notify'].nil?
      form_params["status"] = opts[:'status'] if !opts[:'status'].nil?
      form_params["strategy"] = opts[:'strategy'] if !opts[:'strategy'].nil?
      form_params["tags"] = @api_client.build_collection_param(opts[:'tags'], :multi) if !opts[:'tags'].nil?
      form_params["teams"] = @api_client.build_collection_param(opts[:'teams'], :multi) if !opts[:'teams'].nil?
      form_params["users"] = @api_client.build_collection_param(opts[:'users'], :multi) if !opts[:'users'].nil?
      form_params["mandatory"] = opts[:'mandatory'] if !opts[:'mandatory'].nil?
      form_params["release_type"] = opts[:'release_type'] if !opts[:'release_type'].nil?
      form_params["private"] = opts[:'private'] if !opts[:'private'].nil?
      form_params["owner_id"] = opts[:'owner_id'] if !opts[:'owner_id'].nil?
      form_params["commit_sha"] = opts[:'commit_sha'] if !opts[:'commit_sha'].nil?
      form_params["build_server_url"] = opts[:'build_server_url'] if !opts[:'build_server_url'].nil?
      form_params["repository_url"] = opts[:'repository_url'] if !opts[:'repository_url'].nil?

      # http body (model)
      post_body = nil
      auth_names = ['token']
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'App')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#apps_upload_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
