/**
 * Hockeyapp Public API wrapper
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */



#include "App.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

App::App()
{
    m_Title = U("");
    m_TitleIsSet = false;
    m_Bundle_identifier = U("");
    m_Bundle_identifierIsSet = false;
    m_Public_identifier = U("");
    m_Public_identifierIsSet = false;
    m_Release_type = 0;
    m_Release_typeIsSet = false;
    m_Platform = U("");
    m_PlatformIsSet = false;
    
}

App::~App()
{
}

void App::validate() 
{
    // TODO: implement validation
}

web::json::value App::toJson() const
{
    web::json::value val = web::json::value::object();
     
    if(m_TitleIsSet)
    {
        val[U("title")] = ModelBase::toJson(m_Title);
    }
    if(m_Bundle_identifierIsSet)
    {
        val[U("bundle_identifier")] = ModelBase::toJson(m_Bundle_identifier);
    }
    if(m_Public_identifierIsSet)
    {
        val[U("public_identifier")] = ModelBase::toJson(m_Public_identifier);
    }
    if(m_Release_typeIsSet)
    {
        val[U("release_type")] = ModelBase::toJson(m_Release_type);
    }
    if(m_PlatformIsSet)
    {
        val[U("platform")] = ModelBase::toJson(m_Platform);
    }
    

    return val;
}

void App::fromJson(web::json::value& val)
{
    if(val.has_field(U("title")))
    {
        setTitle(ModelBase::stringFromJson(val[U("title")]));
                
    }
    if(val.has_field(U("bundle_identifier")))
    {
        setBundleIdentifier(ModelBase::stringFromJson(val[U("bundle_identifier")]));
                
    }
    if(val.has_field(U("public_identifier")))
    {
        setPublicIdentifier(ModelBase::stringFromJson(val[U("public_identifier")]));
                
    }
    if(val.has_field(U("release_type")))
    {
        setReleaseType(ModelBase::int32_tFromJson(val[U("release_type")]));
    }
    if(val.has_field(U("platform")))
    {
        setPlatform(ModelBase::stringFromJson(val[U("platform")]));
                
    }
    
}

void App::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    if(m_TitleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("title"), m_Title));
                
    }
    if(m_Bundle_identifierIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("bundle_identifier"), m_Bundle_identifier));
                
    }
    if(m_Public_identifierIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("public_identifier"), m_Public_identifier));
                
    }
    if(m_Release_typeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("release_type"), m_Release_type));
    }
    if(m_PlatformIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("platform"), m_Platform));
                
    }
    
}

void App::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    if(multipart->hasContent(U("title")))
    {
        setTitle(ModelBase::stringFromHttpContent(multipart->getContent(U("title"))));
                
    }
    if(multipart->hasContent(U("bundle_identifier")))
    {
        setBundleIdentifier(ModelBase::stringFromHttpContent(multipart->getContent(U("bundle_identifier"))));
                
    }
    if(multipart->hasContent(U("public_identifier")))
    {
        setPublicIdentifier(ModelBase::stringFromHttpContent(multipart->getContent(U("public_identifier"))));
                
    }
    if(multipart->hasContent(U("release_type")))
    {
        setReleaseType(ModelBase::int32_tFromHttpContent(multipart->getContent(U("release_type"))));
    }
    if(multipart->hasContent(U("platform")))
    {
        setPlatform(ModelBase::stringFromHttpContent(multipart->getContent(U("platform"))));
                
    }
    
}
    
   
utility::string_t App::getTitle() const
{
    return m_Title;
}
void App::setTitle(utility::string_t value)
{
    m_Title = value;
    m_TitleIsSet = true;
}
bool App::titleIsSet() const
{
    return m_TitleIsSet;
}
void App::unsetTitle() 
{
    m_TitleIsSet = false;
}
utility::string_t App::getBundleIdentifier() const
{
    return m_Bundle_identifier;
}
void App::setBundleIdentifier(utility::string_t value)
{
    m_Bundle_identifier = value;
    m_Bundle_identifierIsSet = true;
}
bool App::bundle_identifierIsSet() const
{
    return m_Bundle_identifierIsSet;
}
void App::unsetBundle_identifier() 
{
    m_Bundle_identifierIsSet = false;
}
utility::string_t App::getPublicIdentifier() const
{
    return m_Public_identifier;
}
void App::setPublicIdentifier(utility::string_t value)
{
    m_Public_identifier = value;
    m_Public_identifierIsSet = true;
}
bool App::public_identifierIsSet() const
{
    return m_Public_identifierIsSet;
}
void App::unsetPublic_identifier() 
{
    m_Public_identifierIsSet = false;
}
int32_t App::getReleaseType() const
{
    return m_Release_type;
}
void App::setReleaseType(int32_t value)
{
    m_Release_type = value;
    m_Release_typeIsSet = true;
}
bool App::release_typeIsSet() const
{
    return m_Release_typeIsSet;
}
void App::unsetRelease_type() 
{
    m_Release_typeIsSet = false;
}
utility::string_t App::getPlatform() const
{
    return m_Platform;
}
void App::setPlatform(utility::string_t value)
{
    m_Platform = value;
    m_PlatformIsSet = true;
}
bool App::platformIsSet() const
{
    return m_PlatformIsSet;
}
void App::unsetPlatform() 
{
    m_PlatformIsSet = false;
}

}
}
}
}

