//
// AppsApps.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class AppsApps: JSONEncodable {
    public enum Platform: String { 
        case Ios = "iOS"
        case Android = "Android"
        case MacOs = "Mac Os"
        case WindowsPhone = "Windows Phone"
        case Custom = "Custom"
    }
    public var title: String?
    public var bundleIdentifier: String?
    public var publicIdentifier: String?
    public var deviceFamily: String?
    public var minimumOsVersion: String?
    public var releaseType: Int32?
    public var status: Int32?
    public var platform: Platform?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["title"] = self.title
        nillableDictionary["bundle_identifier"] = self.bundleIdentifier
        nillableDictionary["public_identifier"] = self.publicIdentifier
        nillableDictionary["device_family"] = self.deviceFamily
        nillableDictionary["minimum_os_version"] = self.minimumOsVersion
        nillableDictionary["release_type"] = self.releaseType?.encodeToJSON()
        nillableDictionary["status"] = self.status?.encodeToJSON()
        nillableDictionary["platform"] = self.platform?.rawValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
