/**
 * Hockeyapp Public API wrapper
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * SWGApps_apps.h
 * 
 * 
 */

#ifndef SWGApps_apps_H_
#define SWGApps_apps_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGApps_apps: public SWGObject {
public:
    SWGApps_apps();
    SWGApps_apps(QString* json);
    virtual ~SWGApps_apps();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGApps_apps* fromJson(QString &jsonString);

    QString* getTitle();
    void setTitle(QString* title);
QString* getBundleIdentifier();
    void setBundleIdentifier(QString* bundle_identifier);
QString* getPublicIdentifier();
    void setPublicIdentifier(QString* public_identifier);
QString* getDeviceFamily();
    void setDeviceFamily(QString* device_family);
QString* getMinimumOsVersion();
    void setMinimumOsVersion(QString* minimum_os_version);
qint32 getReleaseType();
    void setReleaseType(qint32 release_type);
qint32 getStatus();
    void setStatus(qint32 status);
QString* getPlatform();
    void setPlatform(QString* platform);

private:
    QString* title;
QString* bundle_identifier;
QString* public_identifier;
QString* device_family;
QString* minimum_os_version;
qint32 release_type;
qint32 status;
QString* platform;
};

} /* namespace Swagger */

#endif /* SWGApps_apps_H_ */
