/**
 * Hockeyapp Public API wrapper
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * SWGApp.h
 * 
 * 
 */

#ifndef SWGApp_H_
#define SWGApp_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGApp: public SWGObject {
public:
    SWGApp();
    SWGApp(QString* json);
    virtual ~SWGApp();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGApp* fromJson(QString &jsonString);

    QString* getTitle();
    void setTitle(QString* title);
QString* getBundleIdentifier();
    void setBundleIdentifier(QString* bundle_identifier);
QString* getPublicIdentifier();
    void setPublicIdentifier(QString* public_identifier);
qint32 getReleaseType();
    void setReleaseType(qint32 release_type);
QString* getPlatform();
    void setPlatform(QString* platform);

private:
    QString* title;
QString* bundle_identifier;
QString* public_identifier;
qint32 release_type;
QString* platform;
};

} /* namespace Swagger */

#endif /* SWGApp_H_ */
