/**
 * Hockeyapp Public API wrapper
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * SWGApps.h
 * 
 * 
 */

#ifndef SWGApps_H_
#define SWGApps_H_

#include <QJsonObject>


#include "SWGApps_apps.h"
#include <QList>
#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGApps: public SWGObject {
public:
    SWGApps();
    SWGApps(QString* json);
    virtual ~SWGApps();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGApps* fromJson(QString &jsonString);

    QString* getSuccess();
    void setSuccess(QString* success);
QList<SWGApps_apps*>* getApps();
    void setApps(QList<SWGApps_apps*>* apps);

private:
    QString* success;
QList<SWGApps_apps*>* apps;
};

} /* namespace Swagger */

#endif /* SWGApps_H_ */
