/**
 * Hockeyapp Public API wrapper
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGApp.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGApp::SWGApp(QString* json) {
    init();
    this->fromJson(*json);
}

SWGApp::SWGApp() {
    init();
}

SWGApp::~SWGApp() {
    this->cleanup();
}

void
SWGApp::init() {
    title = new QString("");
bundle_identifier = new QString("");
public_identifier = new QString("");
release_type = 0;
platform = new QString("");
}

void
SWGApp::cleanup() {
    if(title != NULL) {
        delete title;
    }
if(bundle_identifier != NULL) {
        delete bundle_identifier;
    }
if(public_identifier != NULL) {
        delete public_identifier;
    }

if(platform != NULL) {
        delete platform;
    }
}

SWGApp*
SWGApp::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGApp::fromJsonObject(QJsonObject &pJson) {
    setValue(&title, pJson["title"], "QString", "QString");
setValue(&bundle_identifier, pJson["bundle_identifier"], "QString", "QString");
setValue(&public_identifier, pJson["public_identifier"], "QString", "QString");
setValue(&release_type, pJson["release_type"], "qint32", "");
setValue(&platform, pJson["platform"], "QString", "QString");
}

QString
SWGApp::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGApp::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    
    toJsonValue(QString("title"), title, obj, QString("QString"));
    
        

    
    toJsonValue(QString("bundle_identifier"), bundle_identifier, obj, QString("QString"));
    
        

    
    toJsonValue(QString("public_identifier"), public_identifier, obj, QString("QString"));
    
        
obj->insert("release_type", QJsonValue(release_type));

    
    toJsonValue(QString("platform"), platform, obj, QString("QString"));
    
        

    return obj;
}

QString*
SWGApp::getTitle() {
    return title;
}
void
SWGApp::setTitle(QString* title) {
    this->title = title;
}

QString*
SWGApp::getBundleIdentifier() {
    return bundle_identifier;
}
void
SWGApp::setBundleIdentifier(QString* bundle_identifier) {
    this->bundle_identifier = bundle_identifier;
}

QString*
SWGApp::getPublicIdentifier() {
    return public_identifier;
}
void
SWGApp::setPublicIdentifier(QString* public_identifier) {
    this->public_identifier = public_identifier;
}

qint32
SWGApp::getReleaseType() {
    return release_type;
}
void
SWGApp::setReleaseType(qint32 release_type) {
    this->release_type = release_type;
}

QString*
SWGApp::getPlatform() {
    return platform;
}
void
SWGApp::setPlatform(QString* platform) {
    this->platform = platform;
}



} /* namespace Swagger */

