=begin
#Hockeyapp Public API wrapper

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.0.2

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::DefaultApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @instance = SwaggerClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instact of DefaultApi' do
      expect(@instance).to be_instance_of(SwaggerClient::DefaultApi)
    end
  end

  # unit tests for apps_get
  # 
  # Gets &#x60;Apps&#x60;. 
  # @param [Hash] opts the optional parameters
  # @return [Apps]
  describe 'apps_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for apps_upload_post
  # 
  # Upload a new app
  # @param ipa file data of the .ipa for iOS, .app.zip for OS X, or .apk file for Android
  # @param [Hash] opts the optional parameters
  # @option opts [File] :dsym file data of the .dSYM.zip file (iOS and OS X) or mapping.txt (Android); note that the extension has to be .dsym.zip (case-insensitive) for iOS and OS X and the file name has to be mapping.txt for Android.
  # @option opts [String] :notes release notes as Textile or Markdown (after 5k characters note are truncated)
  # @option opts [Integer] :notes_type type of release notes. &#x60;0&#x60; for Textile, &#x60;1&#x60; for Markdown
  # @option opts [Integer] :notify notify testers (can only be set with full-access tokens). &#x60;0&#x60; to not notify, &#x60;1&#x60; to notify all testers that can install this app,  &#x60;2&#x60; to notify all testers
  # @option opts [Integer] :status download status (can only be set with full-access tokens). &#x60;1&#x60; to not allow users to download the version, &#x60;2&#x60; to make the version available for download
  # @option opts [String] :strategy replace or add build with same build number. &#x60;add&#x60; to add the build as a new build to even if it has the same build number __default__, &#x60;replace&#x60; to replace to a build with the same build number
  # @option opts [Array<String>] :tags restrict download to comma-separated list of tags
  # @option opts [Array<Integer>] :teams restrict download to comma-separated list of team IDs
  # @option opts [Array<Integer>] :users restrict download to comma-separated list of user IDs
  # @option opts [Integer] :mandatory set version as mandatory &#x60;0&#x60; for not mandatory __default__, &#x60;1&#x60; for mandatory
  # @option opts [Integer] :release_type set the release type of the app. &#x60;0&#x60; for beta __default__  &#x60;1&#x60; for store &#x60;2&#x60; for alpha &#x60;3&#x60; for enterprise
  # @option opts [BOOLEAN] :private set to &#x60;true&#x60; to enable the private download page (default is &#x60;true&#x60;)
  # @option opts [Integer] :owner_id set to the ID of your organization
  # @option opts [String] :commit_sha set to the git commit sha for this build
  # @option opts [String] :build_server_url set to the URL of the build job on your build server
  # @option opts [String] :repository_url set to your source repository
  # @return [App]
  describe 'apps_upload_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
