/**
 * Hockeyapp Public API wrapper
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class App {
  
  @SerializedName("title")
  private String title = null;
  @SerializedName("bundle_identifier")
  private String bundleIdentifier = null;
  @SerializedName("public_identifier")
  private String publicIdentifier = null;
  @SerializedName("release_type")
  private Integer releaseType = null;
  public enum PlatformEnum {
     iOS,  Android,  Mac Os,  Windows Phone,  Custom, 
  };
  @SerializedName("platform")
  private PlatformEnum platform = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getBundleIdentifier() {
    return bundleIdentifier;
  }
  public void setBundleIdentifier(String bundleIdentifier) {
    this.bundleIdentifier = bundleIdentifier;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPublicIdentifier() {
    return publicIdentifier;
  }
  public void setPublicIdentifier(String publicIdentifier) {
    this.publicIdentifier = publicIdentifier;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getReleaseType() {
    return releaseType;
  }
  public void setReleaseType(Integer releaseType) {
    this.releaseType = releaseType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public PlatformEnum getPlatform() {
    return platform;
  }
  public void setPlatform(PlatformEnum platform) {
    this.platform = platform;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    App app = (App) o;
    return (this.title == null ? app.title == null : this.title.equals(app.title)) &&
        (this.bundleIdentifier == null ? app.bundleIdentifier == null : this.bundleIdentifier.equals(app.bundleIdentifier)) &&
        (this.publicIdentifier == null ? app.publicIdentifier == null : this.publicIdentifier.equals(app.publicIdentifier)) &&
        (this.releaseType == null ? app.releaseType == null : this.releaseType.equals(app.releaseType)) &&
        (this.platform == null ? app.platform == null : this.platform.equals(app.platform));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.title == null ? 0: this.title.hashCode());
    result = 31 * result + (this.bundleIdentifier == null ? 0: this.bundleIdentifier.hashCode());
    result = 31 * result + (this.publicIdentifier == null ? 0: this.publicIdentifier.hashCode());
    result = 31 * result + (this.releaseType == null ? 0: this.releaseType.hashCode());
    result = 31 * result + (this.platform == null ? 0: this.platform.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class App {\n");
    
    sb.append("  title: ").append(title).append("\n");
    sb.append("  bundleIdentifier: ").append(bundleIdentifier).append("\n");
    sb.append("  publicIdentifier: ").append(publicIdentifier).append("\n");
    sb.append("  releaseType: ").append(releaseType).append("\n");
    sb.append("  platform: ").append(platform).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
