/**
 * Hockeyapp Public API wrapper
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class AppsApps {
  
  @SerializedName("title")
  private String title = null;
  @SerializedName("bundle_identifier")
  private String bundleIdentifier = null;
  @SerializedName("public_identifier")
  private String publicIdentifier = null;
  @SerializedName("device_family")
  private String deviceFamily = null;
  @SerializedName("minimum_os_version")
  private String minimumOsVersion = null;
  @SerializedName("release_type")
  private Integer releaseType = null;
  @SerializedName("status")
  private Integer status = null;
  public enum PlatformEnum {
     iOS,  Android,  Mac Os,  Windows Phone,  Custom, 
  };
  @SerializedName("platform")
  private PlatformEnum platform = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getBundleIdentifier() {
    return bundleIdentifier;
  }
  public void setBundleIdentifier(String bundleIdentifier) {
    this.bundleIdentifier = bundleIdentifier;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPublicIdentifier() {
    return publicIdentifier;
  }
  public void setPublicIdentifier(String publicIdentifier) {
    this.publicIdentifier = publicIdentifier;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDeviceFamily() {
    return deviceFamily;
  }
  public void setDeviceFamily(String deviceFamily) {
    this.deviceFamily = deviceFamily;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMinimumOsVersion() {
    return minimumOsVersion;
  }
  public void setMinimumOsVersion(String minimumOsVersion) {
    this.minimumOsVersion = minimumOsVersion;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getReleaseType() {
    return releaseType;
  }
  public void setReleaseType(Integer releaseType) {
    this.releaseType = releaseType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getStatus() {
    return status;
  }
  public void setStatus(Integer status) {
    this.status = status;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public PlatformEnum getPlatform() {
    return platform;
  }
  public void setPlatform(PlatformEnum platform) {
    this.platform = platform;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppsApps appsApps = (AppsApps) o;
    return (this.title == null ? appsApps.title == null : this.title.equals(appsApps.title)) &&
        (this.bundleIdentifier == null ? appsApps.bundleIdentifier == null : this.bundleIdentifier.equals(appsApps.bundleIdentifier)) &&
        (this.publicIdentifier == null ? appsApps.publicIdentifier == null : this.publicIdentifier.equals(appsApps.publicIdentifier)) &&
        (this.deviceFamily == null ? appsApps.deviceFamily == null : this.deviceFamily.equals(appsApps.deviceFamily)) &&
        (this.minimumOsVersion == null ? appsApps.minimumOsVersion == null : this.minimumOsVersion.equals(appsApps.minimumOsVersion)) &&
        (this.releaseType == null ? appsApps.releaseType == null : this.releaseType.equals(appsApps.releaseType)) &&
        (this.status == null ? appsApps.status == null : this.status.equals(appsApps.status)) &&
        (this.platform == null ? appsApps.platform == null : this.platform.equals(appsApps.platform));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.title == null ? 0: this.title.hashCode());
    result = 31 * result + (this.bundleIdentifier == null ? 0: this.bundleIdentifier.hashCode());
    result = 31 * result + (this.publicIdentifier == null ? 0: this.publicIdentifier.hashCode());
    result = 31 * result + (this.deviceFamily == null ? 0: this.deviceFamily.hashCode());
    result = 31 * result + (this.minimumOsVersion == null ? 0: this.minimumOsVersion.hashCode());
    result = 31 * result + (this.releaseType == null ? 0: this.releaseType.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.platform == null ? 0: this.platform.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppsApps {\n");
    
    sb.append("  title: ").append(title).append("\n");
    sb.append("  bundleIdentifier: ").append(bundleIdentifier).append("\n");
    sb.append("  publicIdentifier: ").append(publicIdentifier).append("\n");
    sb.append("  deviceFamily: ").append(deviceFamily).append("\n");
    sb.append("  minimumOsVersion: ").append(minimumOsVersion).append("\n");
    sb.append("  releaseType: ").append(releaseType).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  platform: ").append(platform).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
