/**
 * Hockeyapp Public API wrapper
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef _SWG_SWGDefaultApi_H_
#define _SWG_SWGDefaultApi_H_

#include "SWGHttpRequest.h"

#include "SWGApps.h"
#include <QString>
#include "SWGApp.h"
#include "SWGHttpRequest.h"

#include <QObject>

namespace Swagger {

class SWGDefaultApi: public QObject {
    Q_OBJECT

public:
    SWGDefaultApi();
    SWGDefaultApi(QString host, QString basePath);
    ~SWGDefaultApi();

    QString host;
    QString basePath;

    void appsGet();
    void appsUploadPost(SWGHttpRequestInputFileElement* ipa, SWGHttpRequestInputFileElement* dsym, QString* notes, qint32 notesType, qint32 notify, qint32 status, QString* strategy, QList<QString*>* tags, QList<qint32>* teams, QList<qint32>* users, qint32 mandatory, qint32 releaseType, bool private, qint32 ownerId, QString* commitSha, QString* buildServerUrl, QString* repositoryUrl);
    
private:
    void appsGetCallback (HttpRequestWorker * worker);
    void appsUploadPostCallback (HttpRequestWorker * worker);
    
signals:
    void appsGetSignal(SWGApps* summary);
    void appsUploadPostSignal(SWGApp* summary);
    
};
}
#endif
