/* 
 * Hockeyapp Public API wrapper
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

type AppsApps struct {

	Title string `json:"title,omitempty"`

	BundleIdentifier string `json:"bundle_identifier,omitempty"`

	PublicIdentifier string `json:"public_identifier,omitempty"`

	DeviceFamily string `json:"device_family,omitempty"`

	MinimumOsVersion string `json:"minimum_os_version,omitempty"`

	ReleaseType int32 `json:"release_type,omitempty"`

	Status int32 `json:"status,omitempty"`

	Platform string `json:"platform,omitempty"`
}
