/*
 * Hockeyapp Public API wrapper
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * AppsApps
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-10-25T14:47:07.790Z")
public class AppsApps {
  @SerializedName("title")
  private String title = null;

  @SerializedName("bundle_identifier")
  private String bundleIdentifier = null;

  @SerializedName("public_identifier")
  private String publicIdentifier = null;

  @SerializedName("device_family")
  private String deviceFamily = null;

  @SerializedName("minimum_os_version")
  private String minimumOsVersion = null;

  @SerializedName("release_type")
  private Integer releaseType = null;

  @SerializedName("status")
  private Integer status = null;

  /**
   * Gets or Sets platform
   */
  public enum PlatformEnum {
    @SerializedName("iOS")
    IOS("iOS"),
    
    @SerializedName("Android")
    ANDROID("Android"),
    
    @SerializedName("Mac Os")
    MAC_OS("Mac Os"),
    
    @SerializedName("Windows Phone")
    WINDOWS_PHONE("Windows Phone"),
    
    @SerializedName("Custom")
    CUSTOM("Custom");

    private String value;

    PlatformEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("platform")
  private PlatformEnum platform = null;

  public AppsApps title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public AppsApps bundleIdentifier(String bundleIdentifier) {
    this.bundleIdentifier = bundleIdentifier;
    return this;
  }

   /**
   * Get bundleIdentifier
   * @return bundleIdentifier
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBundleIdentifier() {
    return bundleIdentifier;
  }

  public void setBundleIdentifier(String bundleIdentifier) {
    this.bundleIdentifier = bundleIdentifier;
  }

  public AppsApps publicIdentifier(String publicIdentifier) {
    this.publicIdentifier = publicIdentifier;
    return this;
  }

   /**
   * Get publicIdentifier
   * @return publicIdentifier
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPublicIdentifier() {
    return publicIdentifier;
  }

  public void setPublicIdentifier(String publicIdentifier) {
    this.publicIdentifier = publicIdentifier;
  }

  public AppsApps deviceFamily(String deviceFamily) {
    this.deviceFamily = deviceFamily;
    return this;
  }

   /**
   * Get deviceFamily
   * @return deviceFamily
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDeviceFamily() {
    return deviceFamily;
  }

  public void setDeviceFamily(String deviceFamily) {
    this.deviceFamily = deviceFamily;
  }

  public AppsApps minimumOsVersion(String minimumOsVersion) {
    this.minimumOsVersion = minimumOsVersion;
    return this;
  }

   /**
   * Get minimumOsVersion
   * @return minimumOsVersion
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMinimumOsVersion() {
    return minimumOsVersion;
  }

  public void setMinimumOsVersion(String minimumOsVersion) {
    this.minimumOsVersion = minimumOsVersion;
  }

  public AppsApps releaseType(Integer releaseType) {
    this.releaseType = releaseType;
    return this;
  }

   /**
   * Get releaseType
   * @return releaseType
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getReleaseType() {
    return releaseType;
  }

  public void setReleaseType(Integer releaseType) {
    this.releaseType = releaseType;
  }

  public AppsApps status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public AppsApps platform(PlatformEnum platform) {
    this.platform = platform;
    return this;
  }

   /**
   * Get platform
   * @return platform
  **/
  @ApiModelProperty(example = "null", value = "")
  public PlatformEnum getPlatform() {
    return platform;
  }

  public void setPlatform(PlatformEnum platform) {
    this.platform = platform;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppsApps appsApps = (AppsApps) o;
    return Objects.equals(this.title, appsApps.title) &&
        Objects.equals(this.bundleIdentifier, appsApps.bundleIdentifier) &&
        Objects.equals(this.publicIdentifier, appsApps.publicIdentifier) &&
        Objects.equals(this.deviceFamily, appsApps.deviceFamily) &&
        Objects.equals(this.minimumOsVersion, appsApps.minimumOsVersion) &&
        Objects.equals(this.releaseType, appsApps.releaseType) &&
        Objects.equals(this.status, appsApps.status) &&
        Objects.equals(this.platform, appsApps.platform);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, bundleIdentifier, publicIdentifier, deviceFamily, minimumOsVersion, releaseType, status, platform);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppsApps {\n");
    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    bundleIdentifier: ").append(toIndentedString(bundleIdentifier)).append("\n");
    sb.append("    publicIdentifier: ").append(toIndentedString(publicIdentifier)).append("\n");
    sb.append("    deviceFamily: ").append(toIndentedString(deviceFamily)).append("\n");
    sb.append("    minimumOsVersion: ").append(toIndentedString(minimumOsVersion)).append("\n");
    sb.append("    releaseType: ").append(toIndentedString(releaseType)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

