# coding: utf-8

"""
    Hockeyapp Public API wrapper

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class App(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, title=None, bundle_identifier=None, public_identifier=None, release_type=None, platform=None):
        """
        App - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'title': 'str',
            'bundle_identifier': 'str',
            'public_identifier': 'str',
            'release_type': 'int',
            'platform': 'str'
        }

        self.attribute_map = {
            'title': 'title',
            'bundle_identifier': 'bundle_identifier',
            'public_identifier': 'public_identifier',
            'release_type': 'release_type',
            'platform': 'platform'
        }

        self._title = title
        self._bundle_identifier = bundle_identifier
        self._public_identifier = public_identifier
        self._release_type = release_type
        self._platform = platform


    @property
    def title(self):
        """
        Gets the title of this App.


        :return: The title of this App.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """
        Sets the title of this App.


        :param title: The title of this App.
        :type: str
        """

        self._title = title

    @property
    def bundle_identifier(self):
        """
        Gets the bundle_identifier of this App.


        :return: The bundle_identifier of this App.
        :rtype: str
        """
        return self._bundle_identifier

    @bundle_identifier.setter
    def bundle_identifier(self, bundle_identifier):
        """
        Sets the bundle_identifier of this App.


        :param bundle_identifier: The bundle_identifier of this App.
        :type: str
        """

        self._bundle_identifier = bundle_identifier

    @property
    def public_identifier(self):
        """
        Gets the public_identifier of this App.


        :return: The public_identifier of this App.
        :rtype: str
        """
        return self._public_identifier

    @public_identifier.setter
    def public_identifier(self, public_identifier):
        """
        Sets the public_identifier of this App.


        :param public_identifier: The public_identifier of this App.
        :type: str
        """

        self._public_identifier = public_identifier

    @property
    def release_type(self):
        """
        Gets the release_type of this App.


        :return: The release_type of this App.
        :rtype: int
        """
        return self._release_type

    @release_type.setter
    def release_type(self, release_type):
        """
        Sets the release_type of this App.


        :param release_type: The release_type of this App.
        :type: int
        """

        self._release_type = release_type

    @property
    def platform(self):
        """
        Gets the platform of this App.


        :return: The platform of this App.
        :rtype: str
        """
        return self._platform

    @platform.setter
    def platform(self, platform):
        """
        Sets the platform of this App.


        :param platform: The platform of this App.
        :type: str
        """
        allowed_values = ["iOS", "Android", "Mac Os", "Windows Phone", "Custom"]
        if platform not in allowed_values:
            raise ValueError(
                "Invalid value for `platform` ({0}), must be one of {1}"
                .format(platform, allowed_values)
            )

        self._platform = platform

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
