/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class Apps_apps (
  title: Option[String],
  bundleIdentifier: Option[String],
  publicIdentifier: Option[String],
  deviceFamily: Option[String],
  minimumOsVersion: Option[String],
  releaseType: Option[Int],
  status: Option[Int],
  platform: Option[Apps_appsEnums.Platform]
) extends ApiModel

object Apps_appsEnums {

  type Platform = Platform.Value
  object Platform extends Enumeration {
    val IOS = Value("iOS")
    val Android = Value("Android")
    val `Mac Os` = Value("Mac Os")
    val `Windows Phone` = Value("Windows Phone")
    val Custom = Value("Custom")
  }

}

