/*
 * Hockeyapp Public API wrapper
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.github.panthro.hockeyapp;

import com.github.panthro.ApiException;
import io.swagger.client.model.Apps;
import io.swagger.client.model.App;
import java.io.File;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * 
     *
     * delete an existing app
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void appsAppIdDeleteTest() throws ApiException {
        String appId = null;
        // api.appsAppIdDelete(appId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Gets &#x60;Apps&#x60;. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void appsGetTest() throws ApiException {
        // Apps response = api.appsGet();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Upload a new app
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void appsUploadPostTest() throws ApiException {
        File ipa = null;
        File dsym = null;
        String notes = null;
        Integer notesType = null;
        Integer notify = null;
        Integer status = null;
        String strategy = null;
        List<String> tags = null;
        List<Integer> teams = null;
        List<Integer> users = null;
        Integer mandatory = null;
        Integer releaseType = null;
        Boolean _private = null;
        Integer ownerId = null;
        String commitSha = null;
        String buildServerUrl = null;
        String repositoryUrl = null;
        // App response = api.appsUploadPost(ipa, dsym, notes, notesType, notify, status, strategy, tags, teams, users, mandatory, releaseType, _private, ownerId, commitSha, buildServerUrl, repositoryUrl);

        // TODO: test validations
    }
    
}
